/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrgSlugRouteRouteImport } from './routes/$orgSlug/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugIndexRouteImport } from './routes/$orgSlug/index'
import { Route as organizationGettingStartedRouteImport } from './routes/(organization)/getting-started'
import { Route as organizationCreateOrganizationRouteImport } from './routes/(organization)/create-organization'
import { Route as organizationAcceptInvitationRouteImport } from './routes/(organization)/accept-invitation'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as OrgSlugpeopleEmployeesRouteImport } from './routes/$orgSlug/(people)/employees'
import { Route as OrgSlugcompanyVisitorsRouteImport } from './routes/$orgSlug/(company)/visitors'
import { Route as OrgSlugcompanySettingsRouteImport } from './routes/$orgSlug/(company)/settings'
import { Route as OrgSlugcompanySchedulesRouteImport } from './routes/$orgSlug/(company)/schedules'
import { Route as OrgSlugcompanyPermissionsRouteImport } from './routes/$orgSlug/(company)/permissions'
import { Route as OrgSlugcompanyLocationsRouteImport } from './routes/$orgSlug/(company)/locations'
import { Route as OrgSlugcompanyAttendanceRouteImport } from './routes/$orgSlug/(company)/attendance'
import { Route as OrgSlugcompanyAnnouncementsRouteImport } from './routes/$orgSlug/(company)/announcements'

const OrgSlugRouteRoute = OrgSlugRouteRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const organizationGettingStartedRoute =
  organizationGettingStartedRouteImport.update({
    id: '/(organization)/getting-started',
    path: '/getting-started',
    getParentRoute: () => rootRouteImport,
  } as any)
const organizationCreateOrganizationRoute =
  organizationCreateOrganizationRouteImport.update({
    id: '/(organization)/create-organization',
    path: '/create-organization',
    getParentRoute: () => rootRouteImport,
  } as any)
const organizationAcceptInvitationRoute =
  organizationAcceptInvitationRouteImport.update({
    id: '/(organization)/accept-invitation',
    path: '/accept-invitation',
    getParentRoute: () => rootRouteImport,
  } as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugpeopleEmployeesRoute = OrgSlugpeopleEmployeesRouteImport.update({
  id: '/(people)/employees',
  path: '/employees',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugcompanyVisitorsRoute = OrgSlugcompanyVisitorsRouteImport.update({
  id: '/(company)/visitors',
  path: '/visitors',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugcompanySettingsRoute = OrgSlugcompanySettingsRouteImport.update({
  id: '/(company)/settings',
  path: '/settings',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugcompanySchedulesRoute = OrgSlugcompanySchedulesRouteImport.update({
  id: '/(company)/schedules',
  path: '/schedules',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugcompanyPermissionsRoute =
  OrgSlugcompanyPermissionsRouteImport.update({
    id: '/(company)/permissions',
    path: '/permissions',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugcompanyLocationsRoute = OrgSlugcompanyLocationsRouteImport.update({
  id: '/(company)/locations',
  path: '/locations',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugcompanyAttendanceRoute =
  OrgSlugcompanyAttendanceRouteImport.update({
    id: '/(company)/attendance',
    path: '/attendance',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugcompanyAnnouncementsRoute =
  OrgSlugcompanyAnnouncementsRouteImport.update({
    id: '/(company)/announcements',
    path: '/announcements',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/accept-invitation': typeof organizationAcceptInvitationRoute
  '/create-organization': typeof organizationCreateOrganizationRoute
  '/getting-started': typeof organizationGettingStartedRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/announcements': typeof OrgSlugcompanyAnnouncementsRoute
  '/$orgSlug/attendance': typeof OrgSlugcompanyAttendanceRoute
  '/$orgSlug/locations': typeof OrgSlugcompanyLocationsRoute
  '/$orgSlug/permissions': typeof OrgSlugcompanyPermissionsRoute
  '/$orgSlug/schedules': typeof OrgSlugcompanySchedulesRoute
  '/$orgSlug/settings': typeof OrgSlugcompanySettingsRoute
  '/$orgSlug/visitors': typeof OrgSlugcompanyVisitorsRoute
  '/$orgSlug/employees': typeof OrgSlugpeopleEmployeesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/accept-invitation': typeof organizationAcceptInvitationRoute
  '/create-organization': typeof organizationCreateOrganizationRoute
  '/getting-started': typeof organizationGettingStartedRoute
  '/$orgSlug': typeof OrgSlugIndexRoute
  '/$orgSlug/announcements': typeof OrgSlugcompanyAnnouncementsRoute
  '/$orgSlug/attendance': typeof OrgSlugcompanyAttendanceRoute
  '/$orgSlug/locations': typeof OrgSlugcompanyLocationsRoute
  '/$orgSlug/permissions': typeof OrgSlugcompanyPermissionsRoute
  '/$orgSlug/schedules': typeof OrgSlugcompanySchedulesRoute
  '/$orgSlug/settings': typeof OrgSlugcompanySettingsRoute
  '/$orgSlug/visitors': typeof OrgSlugcompanyVisitorsRoute
  '/$orgSlug/employees': typeof OrgSlugpeopleEmployeesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(organization)/accept-invitation': typeof organizationAcceptInvitationRoute
  '/(organization)/create-organization': typeof organizationCreateOrganizationRoute
  '/(organization)/getting-started': typeof organizationGettingStartedRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/(company)/announcements': typeof OrgSlugcompanyAnnouncementsRoute
  '/$orgSlug/(company)/attendance': typeof OrgSlugcompanyAttendanceRoute
  '/$orgSlug/(company)/locations': typeof OrgSlugcompanyLocationsRoute
  '/$orgSlug/(company)/permissions': typeof OrgSlugcompanyPermissionsRoute
  '/$orgSlug/(company)/schedules': typeof OrgSlugcompanySchedulesRoute
  '/$orgSlug/(company)/settings': typeof OrgSlugcompanySettingsRoute
  '/$orgSlug/(company)/visitors': typeof OrgSlugcompanyVisitorsRoute
  '/$orgSlug/(people)/employees': typeof OrgSlugpeopleEmployeesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/login'
    | '/signup'
    | '/accept-invitation'
    | '/create-organization'
    | '/getting-started'
    | '/$orgSlug/'
    | '/$orgSlug/announcements'
    | '/$orgSlug/attendance'
    | '/$orgSlug/locations'
    | '/$orgSlug/permissions'
    | '/$orgSlug/schedules'
    | '/$orgSlug/settings'
    | '/$orgSlug/visitors'
    | '/$orgSlug/employees'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/accept-invitation'
    | '/create-organization'
    | '/getting-started'
    | '/$orgSlug'
    | '/$orgSlug/announcements'
    | '/$orgSlug/attendance'
    | '/$orgSlug/locations'
    | '/$orgSlug/permissions'
    | '/$orgSlug/schedules'
    | '/$orgSlug/settings'
    | '/$orgSlug/visitors'
    | '/$orgSlug/employees'
  id:
    | '__root__'
    | '/'
    | '/$orgSlug'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(organization)/accept-invitation'
    | '/(organization)/create-organization'
    | '/(organization)/getting-started'
    | '/$orgSlug/'
    | '/$orgSlug/(company)/announcements'
    | '/$orgSlug/(company)/attendance'
    | '/$orgSlug/(company)/locations'
    | '/$orgSlug/(company)/permissions'
    | '/$orgSlug/(company)/schedules'
    | '/$orgSlug/(company)/settings'
    | '/$orgSlug/(company)/visitors'
    | '/$orgSlug/(people)/employees'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgSlugRouteRoute: typeof OrgSlugRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  organizationAcceptInvitationRoute: typeof organizationAcceptInvitationRoute
  organizationCreateOrganizationRoute: typeof organizationCreateOrganizationRoute
  organizationGettingStartedRoute: typeof organizationGettingStartedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/': {
      id: '/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/(organization)/getting-started': {
      id: '/(organization)/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof organizationGettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(organization)/create-organization': {
      id: '/(organization)/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof organizationCreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(organization)/accept-invitation': {
      id: '/(organization)/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof organizationAcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/(people)/employees': {
      id: '/$orgSlug/(people)/employees'
      path: '/employees'
      fullPath: '/$orgSlug/employees'
      preLoaderRoute: typeof OrgSlugpeopleEmployeesRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/(company)/visitors': {
      id: '/$orgSlug/(company)/visitors'
      path: '/visitors'
      fullPath: '/$orgSlug/visitors'
      preLoaderRoute: typeof OrgSlugcompanyVisitorsRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/(company)/settings': {
      id: '/$orgSlug/(company)/settings'
      path: '/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof OrgSlugcompanySettingsRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/(company)/schedules': {
      id: '/$orgSlug/(company)/schedules'
      path: '/schedules'
      fullPath: '/$orgSlug/schedules'
      preLoaderRoute: typeof OrgSlugcompanySchedulesRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/(company)/permissions': {
      id: '/$orgSlug/(company)/permissions'
      path: '/permissions'
      fullPath: '/$orgSlug/permissions'
      preLoaderRoute: typeof OrgSlugcompanyPermissionsRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/(company)/locations': {
      id: '/$orgSlug/(company)/locations'
      path: '/locations'
      fullPath: '/$orgSlug/locations'
      preLoaderRoute: typeof OrgSlugcompanyLocationsRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/(company)/attendance': {
      id: '/$orgSlug/(company)/attendance'
      path: '/attendance'
      fullPath: '/$orgSlug/attendance'
      preLoaderRoute: typeof OrgSlugcompanyAttendanceRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/(company)/announcements': {
      id: '/$orgSlug/(company)/announcements'
      path: '/announcements'
      fullPath: '/$orgSlug/announcements'
      preLoaderRoute: typeof OrgSlugcompanyAnnouncementsRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
  }
}

interface OrgSlugRouteRouteChildren {
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugcompanyAnnouncementsRoute: typeof OrgSlugcompanyAnnouncementsRoute
  OrgSlugcompanyAttendanceRoute: typeof OrgSlugcompanyAttendanceRoute
  OrgSlugcompanyLocationsRoute: typeof OrgSlugcompanyLocationsRoute
  OrgSlugcompanyPermissionsRoute: typeof OrgSlugcompanyPermissionsRoute
  OrgSlugcompanySchedulesRoute: typeof OrgSlugcompanySchedulesRoute
  OrgSlugcompanySettingsRoute: typeof OrgSlugcompanySettingsRoute
  OrgSlugcompanyVisitorsRoute: typeof OrgSlugcompanyVisitorsRoute
  OrgSlugpeopleEmployeesRoute: typeof OrgSlugpeopleEmployeesRoute
}

const OrgSlugRouteRouteChildren: OrgSlugRouteRouteChildren = {
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugcompanyAnnouncementsRoute: OrgSlugcompanyAnnouncementsRoute,
  OrgSlugcompanyAttendanceRoute: OrgSlugcompanyAttendanceRoute,
  OrgSlugcompanyLocationsRoute: OrgSlugcompanyLocationsRoute,
  OrgSlugcompanyPermissionsRoute: OrgSlugcompanyPermissionsRoute,
  OrgSlugcompanySchedulesRoute: OrgSlugcompanySchedulesRoute,
  OrgSlugcompanySettingsRoute: OrgSlugcompanySettingsRoute,
  OrgSlugcompanyVisitorsRoute: OrgSlugcompanyVisitorsRoute,
  OrgSlugpeopleEmployeesRoute: OrgSlugpeopleEmployeesRoute,
}

const OrgSlugRouteRouteWithChildren = OrgSlugRouteRoute._addFileChildren(
  OrgSlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugRouteRoute: OrgSlugRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  organizationAcceptInvitationRoute: organizationAcceptInvitationRoute,
  organizationCreateOrganizationRoute: organizationCreateOrganizationRoute,
  organizationGettingStartedRoute: organizationGettingStartedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
